; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
data_dir = gifs

[env:esp32s3usbotg]
platform = espressif32
board = esp32s3usbotg
framework = arduino
upload_speed = 921600
monitor_speed = 115200
; upload_port = COM41
; monitor_port = COM41
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder
lib_deps =
  bitbank2/AnimatedGIF @ ^2.2.0
  moononournation/GFX Library for Arduino @ 1.4.9
  ; Waveshare marks Arduino_DriveBus as a manual dependency in the demo bundle.
  ; If PlatformIO does not already find it in your global libraries, copy it to lib/Arduino_DriveBus.
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
; -DBOARD_HAS_PSRAM
monitor_dtr = 0
monitor_rts = 0
